import { z } from 'zod';

const AUDIT_ACTIONS = [
  'COMPANY_CREATED',
  'COMPANY_SUSPENDED',
  'COMPANY_REACTIVATED',
  'USER_LOGIN',
  'USER_LOGOUT',
  'USER_LOGIN_FAILED',
  'USER_ROLE_CHANGED',
  'COMPANY_REQUEST_SUBMITTED',
  'COMPANY_REQUEST_APPROVED',
  'COMPANY_REQUEST_REJECTED',
  'VEHICLE_CREATED',
  'VEHICLE_UPDATED',
  'VEHICLE_ARCHIVED',
  'TIRE_CREATED',
  'TIRE_STATUS_CHANGED',
  'TIRE_DISPOSED',
  'FITMENT_OVERRIDE',
  'INSPECTION_COMPLETED',
  'MAINTENANCE_LOGGED',
  'COMPANY_SETTINGS_UPDATED',
  'USER_INVITED',
  'USER_DEACTIVATED',
  'USER_REACTIVATED',
  'DEPOT_CREATED',
  'DEPOT_UPDATED',
  'DEPOT_ARCHIVED',
  'DEPOT_UNARCHIVED',
  'CATALOG_BRAND_SUBMITTED',
  'CATALOG_MODEL_SUBMITTED',
  'CATALOG_BRAND_APPROVED',
  'CATALOG_BRAND_REJECTED',
  'CATALOG_MODEL_APPROVED',
  'CATALOG_MODEL_REJECTED',
  'VEHICLE_DRIVER_ASSIGNED',
  'VEHICLE_DRIVER_UNASSIGNED',
  'VEHICLE_COMPATIBLE_SIZES_UPDATED',
  'MILEAGE_LOGGED',
  'TIRE_SET_CREATED',
  'TIRE_SET_UPDATED',
  'TIRE_SET_DISSOLVED',
  'TIRES_MOUNTED',
  'TIRES_DISMOUNTED',
  'TIRES_ROTATED',
] as const;

export const auditLogListQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  perPage: z.coerce.number().int().min(1).max(100).default(10),
  action: z.enum(AUDIT_ACTIONS).optional(),
  entityType: z.string().trim().min(1).max(50).optional(),
  search: z.string().trim().max(100).optional(),
  sortOrder: z.enum(['asc', 'desc']).default('desc'),
});

export type AuditLogListQueryInput = z.infer<typeof auditLogListQuerySchema>;
